### ISSUE TITLE
How to config flycheck-aspell?

### ISSUE THREAD

**Issue by hongyi-zhao** [leotaku/flycheck-aspell#13]
On Ubuntu 20.04, I've `aspell` installed:

```
$ aspell --version
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
```
And I installed flycheck-aspell:

`(use-package flycheck-aspell) `

But how to activate it and let it fix the misspelled words automatically?

Regards,
HY

**Comment by leotaku** [comment]
> But how to activate it and let it fix the misspelled words automatically?

I'm not quite sure if you have the correct idea about what flycheck-aspell is supposed to do for you. It will only highlight the misspelled words for you, fixing them is handled by Emacs' Ispell mode.

> But how to activate it

Unfortunately, the setup with Flycheck is somewhat unintuitive, as Flycheck only supports checkers that are specific to modes and not really "global" checkers that are supposed to work for all modes. If you are not already using Flycheck for other things, I would recommend that you switch to Flymake, which is distributed with Emacs and works much better with my spell checking mode. The setup instructions for that are [here](https://github.com/leotaku/flycheck-aspell/blob/master/README-FLYMAKE.md)

If you do want to use Flycheck, which I totally understand why you would, I have just updated the setup instructions [here](https://github.com/leotaku/flycheck-aspell/blob/master/README-FLYCHECK.md) to be more detailed. In case anything is confusing, just tell me, and I'll be happy to help.

**Comment by hongyi-zhao** [comment]
Thank you very much. The last snippet of the directive [here](https://github.com/leotaku/flycheck-aspell/blob/master/README-FLYCHECK.md) should read like this - you omit a `)` at the end:
```emacs-lisp
(advice-add #'ispell-pdict-save :after #'flycheck-maybe-recheck)
(defun flycheck-maybe-recheck (_)
  (when (bound-and-true-p flycheck-mode)
   (flycheck-buffer)))
```
I've tried the following settings based on the above instructions:

```emacs-lisp
(use-package flycheck-aspell)
;; Ensure `flycheck-aspell' is available
(require 'flycheck-aspell)
;; If you want to check TeX/LaTeX/ConTeXt buffers
(add-to-list 'flycheck-checkers 'tex-aspell-dynamic)
;; If you want to check Markdown/GFM buffers
(add-to-list 'flycheck-checkers 'markdown-aspell-dynamic)
;; If you want to check HTML buffers
(add-to-list 'flycheck-checkers 'html-aspell-dynamic)
;; If you want to check XML/SGML buffers
(add-to-list 'flycheck-checkers 'xml-aspell-dynamic)
;; If you want to check Nroff/Troff/Groff buffers
(add-to-list 'flycheck-checkers 'nroff-aspell-dynamic)
;; If you want to check Texinfo buffers
(add-to-list 'flycheck-checkers 'texinfo-aspell-dynamic)
;; If you want to check comments and strings for C-like languages
(add-to-list 'flycheck-checkers 'c-aspell-dynamic)
;; If you want to check message buffers
(add-to-list 'flycheck-checkers 'mail-aspell-dynamic)

(setq ispell-dictionary "en")
(setq ispell-program-name "aspell")
(setq ispell-silently-savep t)

(advice-add #'ispell-pdict-save :after #'flycheck-maybe-recheck)
(defun flycheck-maybe-recheck (_)
  (when (bound-and-true-p flycheck-mode)
   (flycheck-buffer)))
```
But Emacs doesn't hint me the wrong word and suggest changes, as shown below:

![image](https://user-images.githubusercontent.com/11155854/122542913-cde7f980-d05d-11eb-8792-fcfc00882d50.png)

Information about relevant installed packages are shown below:
```
werner@X10DAi:~$ aspell -v
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)

werner@X10DAi:~$ dpkg --get-selections |grep ^aspell
aspell						install
aspell-en					install
```

**Comment by leotaku** [comment]
> The last code snippet of the instructions here should be the following (You omit a ) at the end.):

Thank you, should be fixed on master now. (I have added you as a co-author of the fix, I hope that is alright with you)

> But Emacs doesn't hint me the wrong word and suggest changes, as shown below.

This might be a basic question, but are you sure you have enabled flycheck-mode in your buffer? Try `M-x flycheck-mode` and see if the suggestions appear. 

If that does not work, please run `M-x flycheck-verify-setup` and send me a screenshot of the resulting buffer.

**Comment by hongyi-zhao** [comment]
> I hope that is alright with you

You're welcome.

> are you sure you have enabled flycheck-mode in your buffer?

You're right, and now I add the following line into my init file:

`(add-hook 'after-init-hook #'global-flycheck-mode)`

![image](https://user-images.githubusercontent.com/11155854/122547176-5a94b680-d062-11eb-9156-1fb8057c83de.png)

But I still don't have a convenient way to select an appropriate entry from the candidate correction list.

**Comment by leotaku** [comment]
> But I still don't have a convenient way to select an appropriate entry from the candidate correction list.

As I've said, this is handled by the Emacs Ispell mode. I think the default binding for fixing a misspelled word is `M-$` which is bound to `ispell-word`, but you can of course also add your own keybinding.

With the recommended configurations that you are using, the fixes offered by the `ispell-word` popup will always match the suggestions in the list of corrections shown by flycheck-aspell.

![maim](https://user-images.githubusercontent.com/34915973/122550536-15f22680-d034-11eb-909e-94362acb868b.png)
*This is approximately how it should look, that is without my personal customizations, theme, etc. of course*

**Comment by hongyi-zhao** [comment]
See mine:

![image](https://user-images.githubusercontent.com/11155854/122551214-42736600-d067-11eb-878a-0fcac9be72b5.png)

Is there a more convenient way to select from the list? I have seen the method of re-binding it to the middle mouse button. But TBF, I can't think of the specific command for this trick. I'm rather a newbie to Emacs.

**Comment by leotaku** [comment]
I personally think selecting from the suggestion list is pretty convenient as-is, selecting the fix with just one keystroke. Could you be more specific with what you dislike about it?

> I have seen the method of re-binding it with the mouse button.

Sorry, but I don't quite know what you mean here. If you want the menu that is triggered by middle-clicking with your mouse, you can try the following.

```emacs-lisp
(define-key global-map [mouse-2] #'flyspell-correct-word)
```

Note that while this functionality is provided by the Flyspell package, you do not have to have flyspell-mode enabled for it to work.

**Comment by hongyi-zhao** [comment]
> Could you be more specific with what you dislike about it?

I want to have a drop-down menu, just as we have for command completion with `company`, which is triggered by the threshold of a specific minimum input character number, say, 3, and then incrementally narrowed down as the input sequence increases. 

>  If you want the menu that is triggered by middle-clicking with your mouse, 

Yes.

> (define-key global-map [mouse-2] #'flyspell-correct-word)

I tried with the following code:
```
(add-hook 'after-init-hook #'global-flycheck-mode)
(define-key global-map [mouse-2] #'flyspell-correct-word)
```
And see the screenshot below when I click on the middle button:

![image](https://user-images.githubusercontent.com/11155854/122570107-01d31700-d07e-11eb-94aa-85b778921ae6.png)

**Comment by leotaku** [comment]
> And see the screenshot below when I click on the middle button:

You probably just need to ensure that the Flyspell package has been loaded, i.e. run `(require 'flyspell)`.

> I want to have a drop-down menu, just as we have for command completion with company, which is triggered by...

So you want to also have predictive word suggestions from your dictionaries using something like company? Unfortunately, I do not know of a way to enable something like this reliably.

**Comment by hongyi-zhao** [comment]
> You probably just need to ensure that the Flyspell package has been loaded, i.e. run (require 'flyspell).

No. All your suggested code snippet can't do the job. I found the following workable code snippet from [here](https://stackoverflow.com/questions/6860750/how-to-enable-flyspell-mode-in-emacs-for-all-files-and-all-major-modes):

```emacs-lisp
(use-package flyspell :demand t
   :config
   (use-package 
     flyspell-correct-helm) 
   (defun flyspellCompletion() 
     (flyspell-mode 1) 
     (set (make-local-variable 'company-backends) 
          (copy-tree company-backends)) 
     (add-to-list 'company-backends 'company-ispell)) 
   (defun flyspell-most-modes() 
     (add-hook 'text-mode-hook 'flyspellCompletion) 
     (add-hook 'prog-mode-hook 'flyspellCompletion)
     (dolist (hook '(change-log-mode-hook log-edit-mode-hook)) 
       (add-hook hook (lambda () 
                        (flyspell-mode -1))))) 
   (flyspell-most-modes) 
   :bind (:map flyspell-mode-map
               ("C-." . flyspell-correct-wrapper)))
```
![image](https://user-images.githubusercontent.com/11155854/122575483-647ae180-d083-11eb-9b77-cb10e56a1ca2.png)

> So you want to also have predictive word suggestions from your dictionaries using something like company? 

Yes.

**Comment by leotaku** [comment]
> No. All your suggested code snippet can't do the job.

That surprises me. But good that you found something that works for you.

> > So you want to also have predictive word suggestions from your dictionaries using something like company?

> Yes.

Unfortunately, I won’t be able to help you with that.

**Comment by leotaku** [comment]
I think the initial issue has been solved. If you still have other questions feel free to reopen or start a new issue or discussion.
